// Chief of Staff: graph query helpers.
//
// Loads data/graph.json and provides typed-link queries the agent and other
// tools can call. The graph is regenerated by tools/build-graph.mjs;
// queries here are read-only.
//
// Public API:
//   loadGraph()                                  -> the full graph object
//   stakeholderByName(name)                      -> stakeholder | null
//   openItemsLinkedTo(stakeholderId)             -> queue_item[]
//   itemsByProject(slug)                         -> queue_item[]
//   decisionsByProject(slug)                     -> decision[]
//   decisionsAboutStakeholder(stakeholderId)     -> decision[]
//   warmListDormant(days)                        -> stakeholder[]
//   commitmentsOut()                             -> queue_item[]   (things I owe)
//   commitmentsIn()                              -> queue_item[]   (owed to me)
//   staleProjects()                              -> project[]
//   unresolvedCounterparties()                   -> [{queue_id, raw_name}]
//   meetingsWith(stakeholderId, sinceDays=90)    -> meeting[]
//   topicsWith(stakeholderId, sinceDays=30)      -> string[]
//   mentionedNotMet({minMentions=2})             -> [{raw_name, mentions}]
//   relationshipRhythm(stakeholderId)            -> {total, first, last, avg_days_between, topics}
//
// CLI mode (when invoked directly):
//   node tools/graph-query.mjs warm-list-dormant 45
//   node tools/graph-query.mjs open-for daniel-mercer
//   node tools/graph-query.mjs project anthropic-pm-interview
//   node tools/graph-query.mjs meetings-with mouhssine-rifaki 90
//   node tools/graph-query.mjs topics-with mouhssine-rifaki 30
//   node tools/graph-query.mjs mentioned-not-met 2
//   node tools/graph-query.mjs relationship-rhythm mouhssine-rifaki

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const GRAPH_PATH = path.resolve(__dirname, '..', 'data', 'graph.json');

export function loadGraph() {
  if (!fs.existsSync(GRAPH_PATH)) {
    throw new Error(`graph not found at ${GRAPH_PATH}. Run: node tools/build-graph.mjs`);
  }
  return JSON.parse(fs.readFileSync(GRAPH_PATH, 'utf8'));
}

export function stakeholderByName(name) {
  const g = loadGraph();
  const lower = String(name).toLowerCase();
  return g.stakeholders.find((s) => s.name.toLowerCase() === lower
    || s.id === lower
    || s.name.toLowerCase().split(/\s+/)[0] === lower.split(/\s+/)[0]) ?? null;
}

export function openItemsLinkedTo(stakeholderId) {
  const g = loadGraph();
  const linkedIds = new Set(
    g.edges
      .filter((e) => (e.type === 'item_with' || e.type === 'i_owe' || e.type === 'owed_to_me')
        && e.to === stakeholderId)
      .map((e) => e.from),
  );
  return g.queue_items.filter(
    (i) => linkedIds.has(i.id) && (i.status === 'open' || i.status === 'in-flight'),
  );
}

export function itemsByProject(slug) {
  const g = loadGraph();
  return g.queue_items.filter(
    (i) => i.project === slug && (i.status === 'open' || i.status === 'in-flight'),
  );
}

export function decisionsByProject(slug) {
  const g = loadGraph();
  const linkedIds = new Set(
    g.edges
      .filter((e) => e.type === 'decision_in_project' && e.to === `project:${slug}`)
      .map((e) => e.from),
  );
  return g.decisions.filter((d) => linkedIds.has(d.id));
}

export function decisionsAboutStakeholder(stakeholderId) {
  const g = loadGraph();
  const linkedIds = new Set(
    g.edges
      .filter((e) => e.type === 'mentions' && e.to === stakeholderId)
      .map((e) => e.from),
  );
  return g.decisions.filter((d) => linkedIds.has(d.id));
}

export function warmListDormant(days = 60) {
  const g = loadGraph();
  const today = new Date();
  const cutoff = new Date(today.getTime() - days * 86400000).toISOString().slice(0, 10);
  // Take the most recent of either signal: last_interaction_at (relationships.md)
  // or last_meeting_at (derived from memory/meetings.md via attended edges).
  const last = new Map();
  for (const e of g.edges) {
    if ((e.type === 'last_interaction_at' || e.type === 'last_meeting_at') && e.when) {
      const cur = last.get(e.from);
      if (!cur || e.when > cur) last.set(e.from, e.when);
    }
  }
  return g.stakeholders.filter((s) => {
    const when = last.get(s.id);
    if (!when) return true; // never logged = definitely dormant
    return when < cutoff;
  });
}

export function commitmentsOut() {
  const g = loadGraph();
  return g.queue_items.filter(
    (i) => i.direction === 'out' && (i.status === 'open' || i.status === 'in-flight'),
  );
}

export function commitmentsIn() {
  const g = loadGraph();
  return g.queue_items.filter(
    (i) => i.direction === 'in' && (i.status === 'open' || i.status === 'in-flight'),
  );
}

export function staleProjects() {
  const g = loadGraph();
  const stale = new Set(
    g.edges.filter((e) => e.type === 'project_status_stale').map((e) => e.from),
  );
  return g.projects.filter((p) => stale.has(`project:${p.slug}`));
}

export function unresolvedCounterparties() {
  const g = loadGraph();
  return g.edges
    .filter((e) => e.type === 'item_with_unresolved')
    .map((e) => ({ queue_id: e.from.replace(/^queue:/, ''), raw_name: e.raw_name }));
}

// Meeting-derived helpers. All read from memory/meetings.md via the graph's
// `attended` edges and the meetings array. sinceDays = 0 disables the window.

export function meetingsWith(stakeholderId, sinceDays = 90) {
  const g = loadGraph();
  const cutoff = sinceDays
    ? new Date(Date.now() - sinceDays * 86400000).toISOString().slice(0, 10)
    : null;
  const meetingIds = new Set(
    g.edges
      .filter(
        (e) =>
          e.type === 'attended'
          && e.from === stakeholderId
          && (!cutoff || (e.date && e.date >= cutoff)),
      )
      .map((e) => e.to),
  );
  return (g.meetings ?? [])
    .filter((m) => meetingIds.has(m.id))
    .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));
}

export function topicsWith(stakeholderId, sinceDays = 30) {
  const meetings = meetingsWith(stakeholderId, sinceDays);
  return Array.from(new Set(meetings.map((m) => m.topic).filter(Boolean)));
}

export function mentionedNotMet({ minMentions = 2 } = {}) {
  const g = loadGraph();
  const counts = new Map();
  for (const e of g.edges) {
    if (e.type !== 'attended_unresolved' || !e.raw_name) continue;
    counts.set(e.raw_name, (counts.get(e.raw_name) ?? 0) + 1);
  }
  return Array.from(counts.entries())
    .filter(([, n]) => n >= minMentions)
    .map(([raw_name, mentions]) => ({ raw_name, mentions }))
    .sort((a, b) => b.mentions - a.mentions);
}

export function relationshipRhythm(stakeholderId) {
  const meetings = meetingsWith(stakeholderId, 0);
  if (meetings.length === 0) {
    return { stakeholder_id: stakeholderId, total: 0, first: null, last: null, avg_days_between: null, topics: [] };
  }
  const dates = meetings.map((m) => m.date).filter(Boolean).sort();
  const first = dates[0];
  const last = dates[dates.length - 1];
  let avg = null;
  if (dates.length > 1) {
    const span = (new Date(last).getTime() - new Date(first).getTime()) / 86400000;
    avg = Math.round(span / (dates.length - 1));
  }
  const topics = Array.from(new Set(meetings.map((m) => m.topic).filter(Boolean)));
  return { stakeholder_id: stakeholderId, total: meetings.length, first, last, avg_days_between: avg, topics };
}

// CLI mode
if (process.argv[1] === __filename) {
  const args = process.argv.slice(2);
  const cmd = args[0];
  function jprint(obj) { process.stdout.write(JSON.stringify(obj, null, 2) + '\n'); }
  try {
    switch (cmd) {
      case 'warm-list-dormant':   jprint(warmListDormant(Number(args[1] ?? 60))); break;
      case 'open-for':            jprint(openItemsLinkedTo(args[1])); break;
      case 'project':             jprint({ items: itemsByProject(args[1]), decisions: decisionsByProject(args[1]) }); break;
      case 'commitments-out':     jprint(commitmentsOut()); break;
      case 'commitments-in':      jprint(commitmentsIn()); break;
      case 'stale-projects':      jprint(staleProjects()); break;
      case 'unresolved':          jprint(unresolvedCounterparties()); break;
      case 'meetings-with':       jprint(meetingsWith(args[1], Number(args[2] ?? 90))); break;
      case 'topics-with':         jprint(topicsWith(args[1], Number(args[2] ?? 30))); break;
      case 'mentioned-not-met':   jprint(mentionedNotMet({ minMentions: Number(args[1] ?? 2) })); break;
      case 'relationship-rhythm': jprint(relationshipRhythm(args[1])); break;
      case 'stats':               jprint(loadGraph().stats); break;
      default:
        process.stdout.write(
          'usage: node tools/graph-query.mjs <warm-list-dormant [days] | open-for <id> | project <slug> | commitments-out | commitments-in | stale-projects | unresolved | meetings-with <id> [days] | topics-with <id> [days] | mentioned-not-met [min] | relationship-rhythm <id> | stats>\n',
        );
        process.exit(cmd ? 2 : 0);
    }
  } catch (err) {
    process.stderr.write(`graph-query: ${err.message}\n`);
    process.exit(1);
  }
}
